const client_id = "q1001";
const client_name = "sirius black";
const year = 2024;
const to_date = "12/03/2024";
const headers_data = [
  "N Qty",
  "N Rate",
  "N Amount",
  "Cl Rate",
  "Profit/Loss",
  "Buy Company",
  "Buy Date",
  "Buy Qty",
  "Buy Rate",
  "Buy Amt",
  "Sale Company",
  "Sale Date",
  "Sale Qty",
  "Sale Amt",
  "Sale Rate",
  "Low Rate",
  "Low Amt",
];
const dummy_data = {
  OP_ASSETS: [
    {
      scrip_name: "GODREJ AGROVET LIMITED",
      scrip_code: "540743",
      n_qty: 32,
      n_rate: 460,
      n_amount: -14720,
      cl_rate: 500.05,
      profit_loss: 0,
      buy_company: "BSE_CASH",
      buy_date: "12-10-2017",
      buy_qty: 32,
      buy_rate: 460,
      buy_amt: 14720,
      sale_company: "",
      sale_date: "",
      sale_qty: 0,
      sale_amt: 0,
      sale_rate: 0,
      low_rate: 460,
      low_amt: 14720,
    },
    {
      scrip_name: "SOME OTHER COMPANY",
      scrip_code: "123456",
      n_qty: 50,
      n_rate: 520,
      n_amount: -26000,
      cl_rate: 550.75,
      profit_loss: 0,
      buy_company: "BSE_CASH",
      buy_date: "12-10-2017",
      buy_qty: 50,
      buy_rate: 520,
      buy_amt: 26000,
      sale_company: "",
      sale_date: "",
      sale_qty: 0,
      sale_amt: 0,
      sale_rate: 0,
      low_rate: 520,
      low_amt: 26000,
    },
    {
      scrip_name: "ANOTHER COMPANY",
      scrip_code: "789012",
      n_qty: 20,
      n_rate: 380,
      n_amount: -7600,
      cl_rate: 400.5,
      profit_loss: 0,
      buy_company: "BSE_CASH",
      buy_date: "12-10-2017",
      buy_qty: 20,
      buy_rate: 380,
      buy_amt: 7600,
      sale_company: "",
      sale_date: "",
      sale_qty: 0,
      sale_amt: 0,
      sale_rate: 0,
      low_rate: 380,
      low_amt: 7600,
    },
    {
      scrip_name: "Computer Age Management",
      scrip_code: "789992",
      n_qty: 22,
      n_rate: 490,
      n_amount: -7600,
      cl_rate: 400.5,
      profit_loss: 0,
      buy_company: "BSE_CASH",
      buy_date: "12-10-2017",
      buy_qty: 20,
      buy_rate: 380,
      buy_amt: 7600,
      sale_company: "",
      sale_date: "",
      sale_qty: 0,
      sale_amt: 0,
      sale_rate: 0,
      low_rate: 380,
      low_amt: 7600,
    },
    {
      scrip_name: "Aptus HOusing Fin",
      scrip_code: "789012",
      n_qty: 20,
      n_rate: 380,
      n_amount: -7600,
      cl_rate: 400.5,
      profit_loss: 0,
      buy_company: "BSE_CASH",
      buy_date: "12-10-2017",
      buy_qty: 20,
      buy_rate: 380,
      buy_amt: 7600,
      sale_company: "",
      sale_date: "",
      sale_qty: 0,
      sale_amt: 0,
      sale_rate: 0,
      low_rate: 380,
      low_amt: 7600,
    },
  ],
  SHORTTERM: [
    {
      scrip_name: "HFCL Limited",
      scrip_code: "640740",
      n_qty: 32,
      n_rate: 460,
      n_amount: -14720,
      cl_rate: 500.05,
      profit_loss: 0,
      buy_company: "BSE_CASH",
      buy_date: "12-10-2017",
      buy_qty: 32,
      buy_rate: 460,
      buy_amt: 14720,
      sale_company: "",
      sale_date: "",
      sale_qty: 0,
      sale_amt: 0,
      sale_rate: 0,
      low_rate: 460,
      low_amt: 14720,
    },
    {
      scrip_name: "Lupin Ltd.",
      scrip_code: "223457",
      n_qty: 50,
      n_rate: 520,
      n_amount: -26000,
      cl_rate: 550.75,
      profit_loss: 0,
      buy_company: "BSE_CASH",
      buy_date: "12-10-2017",
      buy_qty: 50,
      buy_rate: 520,
      buy_amt: 26000,
      sale_company: "",
      sale_date: "",
      sale_qty: 0,
      sale_amt: 0,
      sale_rate: 0,
      low_rate: 520,
      low_amt: 26000,
    },
    {
      scrip_name: "Piramal Enterprises ltd",
      scrip_code: "889013",
      n_qty: 20,
      n_rate: 380,
      n_amount: -7600,
      cl_rate: 400.5,
      profit_loss: 0,
      buy_company: "BSE_CASH",
      buy_date: "12-10-2017",
      buy_qty: 20,
      buy_rate: 380,
      buy_amt: 7600,
      sale_company: "",
      sale_date: "",
      sale_qty: 0,
      sale_amt: 0,
      sale_rate: 0,
      low_rate: 380,
      low_amt: 7600,
    },
    {
        scrip_name: "Cipla Ltd.",
        scrip_code: "332457",
        n_qty: 50,
        n_rate: 520,
        n_amount: -26000,
        cl_rate: 550.75,
        profit_loss: 0,
        buy_company: "BSE_CASH",
        buy_date: "12-10-2017",
        buy_qty: 50,
        buy_rate: 520,
        buy_amt: 26000,
        sale_company: "",
        sale_date: "",
        sale_qty: 0,
        sale_amt: 0,
        sale_rate: 0,
        low_rate: 520,
        low_amt: 26000,
      },
  ],
};

export { client_id, client_name, to_date, headers_data, year, dummy_data };
